spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/natc
    username: natc
    password: ENC(4ptjXo7JluhqszGqz1ua3ALLNWo8VQYliL3FqEz0w9dZGwsbrZXFkyITg/zsqtDScjKEvt8LLD0=)
  security:
    user:
      name: natc-client
      password: ENC(V9DPUx2MZ8Knb9N3cFSBN3g6AybkyH5Aa8QvFNjEqUfhGAGKNq369lShlwdECrdML5C9jFfsP1E=)

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: DUMMY

natc:
  league:
    players-per-team: 13
    first-season: 1971
    initial-managers: 80
    initial-players: 600