spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: natc
    password: ENC(wSI15dRY960Ge77lWsvlOQ==)
  security:
    user:
      name: natc-client
      password: ENC(V9DPUx2MZ8Knb9N3cFSBN3g6AybkyH5Aa8QvFNjEqUfhGAGKNq369lShlwdECrdML5C9jFfsP1E=)

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: DUMMY
