name: Application Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '14'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute
        run: ./gradlew clean build